# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 843f81b514267155082ebf53ed555f47a5e59446c1cf1bd56e03f820567ccafd614977781d0e6188ea783202d37e0ee31083efdf06b75ca015eeeb44e1b8bc79

test:
  secret_key_base: f9b4b02efa913f1fc8a1872a559b77beb5059b14bdbe109e5452399ec43ac79881a9007eee13056681ba06d43ff090ef6eb142f78869029d0f471dfa447f3e46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
